In [ ]:
# kaggle of

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\ajupe\anaconda3\lib\site-packages (1.6.6)
Requirement already satisfied: six>=1.10 in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (2023.7.22)
Requirement already satisfied: python-dateutil in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (4.65.0)
Requirement already satisfied: python-slugify in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (1.26.16)
Requirement already satisfied: bleach in c:\users\ajupe\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\ajupe\anaconda3\lib\site-packages (from bleach->kaggle) (23.1)
Requirement already satisfied: webencodings in c:\users\ajupe\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\ajupe\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ajupe\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ajupe\anaconda3\lib\site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: colorama in c:\users\ajupe\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [4]:
!kaggle datasets download -d https://www.kaggle.com/datasets/kabure/retail-bankingdemodata?select=completedtrans.csv

Invalid dataset specification https://www.kaggle.com/datasets/kabure/retail-bankingdemodata?select=completedtrans.csv

In [5]:
!pip install requests

Requirement already satisfied: requests in c:\users\ajupe\anaconda3\lib\site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ajupe\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ajupe\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ajupe\anaconda3\lib\site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ajupe\anaconda3\lib\site-packages (from requests) (2023.7.22)

In [1]:
import requests
import pandas as pd

In [12]:
!kaggle datasets download -d kabure/retail-bankingdemodata

401 - Unauthorized - Unauthenticated

In [2]:
import os

# Make sure kaggle.json is in the current directory and then set KAGGLE_CONFIG_DIR
os.environ['KAGGLE_CONFIG_DIR'] = os.getcwd()

In [3]:
!kaggle datasets download -d kabure/retail-bankingdemodata

Downloading retail-bankingdemodata.zip to C:\Users\ajupe\OneDrive - New Zealand Skills & Education Group\GDDA7123C\GDDA707_Advanced Data Engineering\Assessment-2

  0%|          | 0.00/31.8M [00:00<?, ?B/s]
  3%|3         | 1.00M/31.8M [00:01<00:38, 831kB/s]
  6%|6         | 2.00M/31.8M [00:01<00:18, 1.66MB/s]
  9%|9         | 3.00M/31.8M [00:01<00:11, 2.68MB/s]
 13%|#2        | 4.00M/31.8M [00:01<00:08, 3.33MB/s]
 16%|#5        | 5.00M/31.8M [00:01<00:07, 3.96MB/s]
 19%|#8        | 6.00M/31.8M [00:02<00:05, 4.61MB/s]
 22%|##1       | 7.00M/31.8M [00:02<00:05, 4.98MB/s]
 25%|##5       | 8.00M/31.8M [00:02<00:04, 5.41MB/s]
 28%|##8       | 9.00M/31.8M [00:02<00:04, 5.60MB/s]
 31%|###1      | 10.0M/31.8M [00:02<00:03, 5.80MB/s]
 35%|###4      | 11.0M/31.8M [00:02<00:03, 5.98MB/s]
 38%|###7      | 12.0M/31.8M [00:03<00:03, 6.07MB/s]
 41%|####      | 13.0M/31.8M [00:03<00:03, 6.16MB/s]
 44%|####3     | 14.0M/31.8M [00:03<00:02, 6.52MB/s]
 47%|####7     | 15.0M/31.8M [00:03<00:02, 7.25MB/s]
 50%|#####     | 16.0M/31.8M [00:03<00:02, 6.82MB/s]
 57%|#####6    | 18.0M/31.8M [00:03<00:01, 7.92MB/s]
 60%|#####9    | 19.0M/31.8M [00:04<00:01, 8.09MB/s]
 63%|######2   | 20.0M/31.8M [00:04<00:01, 8.18MB/s]
 66%|######5   | 21.0M/31.8M [00:04<00:01, 6.42MB/s]
 69%|######9   | 22.0M/31.8M [00:04<00:01, 6.35MB/s]
 75%|#######5  | 24.0M/31.8M [00:04<00:01, 7.49MB/s]
 79%|#######8  | 25.0M/31.8M [00:04<00:00, 7.77MB/s]
 82%|########1 | 26.0M/31.8M [00:05<00:00, 7.90MB/s]
 85%|########4 | 27.0M/31.8M [00:05<00:00, 8.03MB/s]
 88%|########7 | 28.0M/31.8M [00:05<00:00, 8.11MB/s]
 91%|#########1| 29.0M/31.8M [00:05<00:00, 8.15MB/s]
 94%|#########4| 30.0M/31.8M [00:05<00:00, 8.22MB/s]
 97%|#########7| 31.0M/31.8M [00:05<00:00, 8.30MB/s]
100%|##########| 31.8M/31.8M [00:05<00:00, 8.31MB/s]
100%|##########| 31.8M/31.8M [00:05<00:00, 5.80MB/s]

In [4]:
from zipfile import ZipFile

# Adjust the file name as necessary
zip_file = "retail-bankingdemodata.zip"

with ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall()

# Optionally, remove the ZIP file after extraction
import os
os.remove(zip_file)

In [5]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('completedtrans.csv')

# Display the first few rows of the DataFrame
df.head()

C:\Users\ajupe\AppData\Local\Temp\ipykernel_20696\2116646077.py:4: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('completedtrans.csv')

,column_a,trans_id,account_id,type,operation,amount,balance,k_symbol,bank,account,year,month,day,fulldate,fulltime,fulldatewithtime,date
0,1,T00695247,A00002378,Credit,Credit in Cash,700.0,700.0,NaN,NaN,NaN,2013,1,1,2013-01-01,11:02:40,2013-01-01T11:02:40,2013-01-01
1,2,T00171812,A00000576,Credit,Credit in Cash,900.0,900.0,NaN,NaN,NaN,2013,1,1,2013-01-01,08:23:33,2013-01-01T08:23:33,2013-01-01
2,3,T00207264,A00000704,Credit,Credit in Cash,1000.0,1000.0,NaN,NaN,NaN,2013,1,1,2013-01-01,15:19:21,2013-01-01T15:19:21,2013-01-01
3,4,T01117247,A00003818,Credit,Credit in Cash,600.0,600.0,NaN,NaN,NaN,2013,1,1,2013-01-01,10:42:35,2013-01-01T10:42:35,2013-01-01
4,5,T00579373,A00001972,Credit,Credit in Cash,400.0,400.0,NaN,NaN,NaN,2013,1,2,2013-01-02,11:39:25,2013-01-02T11:39:25,2013-01-02

In [6]:
df.shape

(1056320, 17)

In [7]:
df.isnull().sum()

column_a                 0
trans_id                 0
account_id               0
type                     0
operation           183114
amount                   0
balance                  0
k_symbol            481881
bank                782812
account             760931
year                     0
month                    0
day                      0
fulldate                 0
fulltime                 0
fulldatewithtime         0
date                     0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1056320 entries, 0 to 1056319
Data columns (total 17 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   column_a          1056320 non-null  int64
 1   trans_id          1056320 non-null  object
 2   account_id        1056320 non-null  object
 3   type              1056320 non-null  object
 4   operation         873206 non-null   object
 5   amount            1056320 non-null  float64
 6   balance           1056320 non-null  float64
 7   k_symbol          574439 non-null   object
 8   bank              273508 non-null   object
 9   account           295389 non-null   float64
 10  year              1056320 non-null  int64
 11  month             1056320 non-null  int64
 12  day               1056320 non-null  int64
 13  fulldate          1056320 non-null  object
 14  fulltime          1056320 non-null  object
 15  fulldatewithtime  1056320 non-null  object
 16  date              1056320 non-null  object
dtypes: float64(3), int64(4), object(10)
memory usage: 137.0+ MB

In [9]:
drop_columns = ['operation', 'k_symbol', 'bank', 'account']

# Assuming 'df' is your DataFrame
df = df.drop(columns=drop_columns)

In [10]:
df.isnull().sum()

column_a            0
trans_id            0
account_id          0
type                0
amount              0
balance             0
year                0
month               0
day                 0
fulldate            0
fulltime            0
fulldatewithtime    0
date                0
dtype: int64

In [18]:
df.drop(columns=['column_a'], inplace=True)

In [19]:
#checking duplicate values 
duplicates = df[df.duplicated()]
duplicates

Empty DataFrame
Columns: [trans_id, account_id, type, amount, balance, year, month, day, fulldate, fulltime, fulldatewithtime, date]
Index: []

In [20]:
df.head(2)

,trans_id,account_id,type,amount,balance,year,month,day,fulldate,fulltime,fulldatewithtime,date
0,T00695247,A00002378,Credit,700.0,700.0,2013,1,1,2013-01-01,11:02:40,2013-01-01T11:02:40,2013-01-01
1,T00171812,A00000576,Credit,900.0,900.0,2013,1,1,2013-01-01,08:23:33,2013-01-01T08:23:33,2013-01-01

In [21]:
#uploading data to MongoDB

In [22]:
#import libraries
import pymongo
import pandas as pd
import json

In [23]:
#connect to mongodb
client = pymongo.MongoClient("mongodb+srv://ajupeter:student2023@mongodbcluster.s7xdaor.mongodb.net/?retryWrites=true&w=majority&appName=MongoDBCluster")

In [24]:
#create a new collection
collection_name = "GDDA707A2"

#convert dataframe to a list of dictionaries
data_list = df.to_dict(orient='records')

In [25]:
#print result
data_list

[{'trans_id': 'T00695247',
  'account_id': 'A00002378',
  'type': 'Credit',
  'amount': 700.0,
  'balance': 700.0,
  'year': 2013,
  'month': 1,
  'day': 1,
  'fulldate': '2013-01-01',
  'fulltime': '11:02:40',
  'fulldatewithtime': '2013-01-01T11:02:40',
  'date': '2013-01-01'},
 {'trans_id': 'T00171812',
  'account_id': 'A00000576',
  'type': 'Credit',
  'amount': 900.0,
  'balance': 900.0,
  'year': 2013,
  'month': 1,
  'day': 1,
  'fulldate': '2013-01-01',
  'fulltime': '08:23:33',
  'fulldatewithtime': '2013-01-01T08:23:33',
  'date': '2013-01-01'},
 {'trans_id': 'T00207264',
  'account_id': 'A00000704',
  'type': 'Credit',
  'amount': 1000.0,
  'balance': 1000.0,
  'year': 2013,
  'month': 1,
  'day': 1,
  'fulldate': '2013-01-01',
  'fulltime': '15:19:21',
  'fulldatewithtime': '2013-01-01T15:19:21',
  'date': '2013-01-01'},
 {'trans_id': 'T01117247',
  'account_id': 'A00003818',
  'type': 'Credit',
  'amount': 600.0,
  'balance': 600.0,
  'year': 2013,
  'month': 1,
  'day': 1,
  'fulldate': '2013-01-01',
  'fulltime': '10:42:35',
  'fulldatewithtime': '2013-01-01T10:42:35',
  'date': '2013-01-01'},
 {'trans_id': 'T00579373',
  'account_id': 'A00001972',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 2,
  'fulldate': '2013-01-02',
  'fulltime': '11:39:25',
  'fulldatewithtime': '2013-01-02T11:39:25',
  'date': '2013-01-02'},
 {'trans_id': 'T00771035',
  'account_id': 'A00002632',
  'type': 'Credit',
  'amount': 1100.0,
  'balance': 1100.0,
  'year': 2013,
  'month': 1,
  'day': 2,
  'fulldate': '2013-01-02',
  'fulltime': '15:15:12',
  'fulldatewithtime': '2013-01-02T15:15:12',
  'date': '2013-01-02'},
 {'trans_id': 'T00452728',
  'account_id': 'A00001539',
  'type': 'Credit',
  'amount': 600.0,
  'balance': 600.0,
  'year': 2013,
  'month': 1,
  'day': 3,
  'fulldate': '2013-01-03',
  'fulltime': '09:34:29',
  'fulldatewithtime': '2013-01-03T09:34:29',
  'date': '2013-01-03'},
 {'trans_id': 'T00725751',
  'account_id': 'A00002484',
  'type': 'Credit',
  'amount': 1100.0,
  'balance': 1100.0,
  'year': 2013,
  'month': 1,
  'day': 3,
  'fulldate': '2013-01-03',
  'fulltime': '09:36:35',
  'fulldatewithtime': '2013-01-03T09:36:35',
  'date': '2013-01-03'},
 {'trans_id': 'T00497211',
  'account_id': 'A00001695',
  'type': 'Credit',
  'amount': 200.0,
  'balance': 200.0,
  'year': 2013,
  'month': 1,
  'day': 3,
  'fulldate': '2013-01-03',
  'fulltime': '15:22:23',
  'fulldatewithtime': '2013-01-03T15:22:23',
  'date': '2013-01-03'},
 {'trans_id': 'T00232960',
  'account_id': 'A00000793',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 3,
  'fulldate': '2013-01-03',
  'fulltime': '15:08:16',
  'fulldatewithtime': '2013-01-03T15:08:16',
  'date': '2013-01-03'},
 {'trans_id': 'T00505240',
  'account_id': 'A00001726',
  'type': 'Credit',
  'amount': 1000.0,
  'balance': 1000.0,
  'year': 2013,
  'month': 1,
  'day': 3,
  'fulldate': '2013-01-03',
  'fulltime': '13:54:49',
  'fulldatewithtime': '2013-01-03T13:54:49',
  'date': '2013-01-03'},
 {'trans_id': 'T00144541',
  'account_id': 'A00000485',
  'type': 'Credit',
  'amount': 300.0,
  'balance': 300.0,
  'year': 2013,
  'month': 1,
  'day': 4,
  'fulldate': '2013-01-04',
  'fulltime': '16:40:53',
  'fulldatewithtime': '2013-01-04T16:40:53',
  'date': '2013-01-04'},
 {'trans_id': 'T00637741',
  'account_id': 'A00002177',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 4,
  'fulldate': '2013-01-04',
  'fulltime': '10:30:59',
  'fulldatewithtime': '2013-01-04T10:30:59',
  'date': '2013-01-04'},
 {'trans_id': 'T00689827',
  'account_id': 'A00002357',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 4,
  'fulldate': '2013-01-04',
  'fulltime': '16:29:16',
  'fulldatewithtime': '2013-01-04T16:29:16',
  'date': '2013-01-04'},
 {'trans_id': 'T00846006',
  'account_id': 'A00002881',
  'type': 'Credit',
  'amount': 700.0,
  'balance': 700.0,
  'year': 2013,
  'month': 1,
  'day': 4,
  'fulldate': '2013-01-04',
  'fulltime': '09:29:01',
  'fulldatewithtime': '2013-01-04T09:29:01',
  'date': '2013-01-04'},
 {'trans_id': 'T00637742',
  'account_id': 'A00002177',
  'type': 'Credit',
  'amount': 5123.0,
  'balance': 5923.0,
  'year': 2013,
  'month': 1,
  'day': 5,
  'fulldate': '2013-01-05',
  'fulltime': '16:44:42',
  'fulldatewithtime': '2013-01-05T16:44:42',
  'date': '2013-01-05'},
 {'trans_id': 'T02908688',
  'account_id': 'A00009635',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 5,
  'fulldate': '2013-01-05',
  'fulltime': '13:32:11',
  'fulldatewithtime': '2013-01-05T13:32:11',
  'date': '2013-01-05'},
 {'trans_id': 'T00232961',
  'account_id': 'A00000793',
  'type': 'Credit',
  'amount': 3401.0,
  'balance': 4201.0,
  'year': 2013,
  'month': 1,
  'day': 5,
  'fulldate': '2013-01-05',
  'fulltime': '11:56:11',
  'fulldatewithtime': '2013-01-05T11:56:11',
  'date': '2013-01-05'},
 {'trans_id': 'T00192096',
  'account_id': 'A00000652',
  'type': 'Credit',
  'amount': 700.0,
  'balance': 700.0,
  'year': 2013,
  'month': 1,
  'day': 5,
  'fulldate': '2013-01-05',
  'fulltime': '09:28:49',
  'fulldatewithtime': '2013-01-05T09:28:49',
  'date': '2013-01-05'},
 {'trans_id': 'T00542215',
  'account_id': 'A00001844',
  'type': 'Credit',
  'amount': 500.0,
  'balance': 500.0,
  'year': 2013,
  'month': 1,
  'day': 6,
  'fulldate': '2013-01-06',
  'fulltime': '14:38:54',
  'fulldatewithtime': '2013-01-06T14:38:54',
  'date': '2013-01-06'},
 {'trans_id': 'T00565654',
  'account_id': 'A00001926',
  'type': 'Credit',
  'amount': 700.0,
  'balance': 700.0,
  'year': 2013,
  'month': 1,
  'day': 6,
  'fulldate': '2013-01-06',
  'fulltime': '11:41:28',
  'fulldatewithtime': '2013-01-06T11:41:28',
  'date': '2013-01-06'},
 {'trans_id': 'T00542216',
  'account_id': 'A00001844',
  'type': 'Credit',
  'amount': 3242.0,
  'balance': 3742.0,
  'year': 2013,
  'month': 1,
  'day': 7,
  'fulldate': '2013-01-07',
  'fulltime': '10:11:45',
  'fulldatewithtime': '2013-01-07T10:11:45',
  'date': '2013-01-07'},
 {'trans_id': 'T01027725',
  'account_id': 'A00003510',
  'type': 'Credit',
  'amount': 500.0,
  'balance': 500.0,
  'year': 2013,
  'month': 1,
  'day': 7,
  'fulldate': '2013-01-07',
  'fulltime': '08:59:48',
  'fulldatewithtime': '2013-01-07T08:59:48',
  'date': '2013-01-07'},
 {'trans_id': 'T00374589',
  'account_id': 'A00001276',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 7,
  'fulldate': '2013-01-07',
  'fulltime': '13:53:48',
  'fulldatewithtime': '2013-01-07T13:53:48',
  'date': '2013-01-07'},
 {'trans_id': 'T00579374',
  'account_id': 'A00001972',
  'type': 'Credit',
  'amount': 5298.0,
  'balance': 5698.0,
  'year': 2013,
  'month': 1,
  'day': 7,
  'fulldate': '2013-01-07',
  'fulltime': '08:09:01',
  'fulldatewithtime': '2013-01-07T08:09:01',
  'date': '2013-01-07'},
 {'trans_id': 'T00699220',
  'account_id': 'A00002393',
  'type': 'Credit',
  'amount': 900.0,
  'balance': 900.0,
  'year': 2013,
  'month': 1,
  'day': 7,
  'fulldate': '2013-01-07',
  'fulltime': '09:44:19',
  'fulldatewithtime': '2013-01-07T09:44:19',
  'date': '2013-01-07'},
 {'trans_id': 'T00129502',
  'account_id': 'A00000435',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '11:33:46',
  'fulldatewithtime': '2013-01-08T11:33:46',
  'date': '2013-01-08'},
 {'trans_id': 'T00374590',
  'account_id': 'A00001276',
  'type': 'Credit',
  'amount': 6774.0,
  'balance': 7174.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '10:41:24',
  'fulldatewithtime': '2013-01-08T10:41:24',
  'date': '2013-01-08'},
 {'trans_id': 'T00057433',
  'account_id': 'A00000192',
  'type': 'Credit',
  'amount': 300.0,
  'balance': 300.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '11:27:40',
  'fulldatewithtime': '2013-01-08T11:27:40',
  'date': '2013-01-08'},
 {'trans_id': 'T00497212',
  'account_id': 'A00001695',
  'type': 'Credit',
  'amount': 11832.0,
  'balance': 12032.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '11:42:14',
  'fulldatewithtime': '2013-01-08T11:42:14',
  'date': '2013-01-08'},
 {'trans_id': 'T00621760',
  'account_id': 'A00002122',
  'type': 'Credit',
  'amount': 300.0,
  'balance': 300.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '13:23:47',
  'fulldatewithtime': '2013-01-08T13:23:47',
  'date': '2013-01-08'},
 {'trans_id': 'T00480214',
  'account_id': 'A00001637',
  'type': 'Credit',
  'amount': 500.0,
  'balance': 500.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '14:01:07',
  'fulldatewithtime': '2013-01-08T14:01:07',
  'date': '2013-01-08'},
 {'trans_id': 'T00612392',
  'account_id': 'A00002087',
  'type': 'Credit',
  'amount': 600.0,
  'balance': 600.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '13:21:14',
  'fulldatewithtime': '2013-01-08T13:21:14',
  'date': '2013-01-08'},
 {'trans_id': 'T00224342',
  'account_id': 'A00000764',
  'type': 'Credit',
  'amount': 1100.0,
  'balance': 1100.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '10:25:46',
  'fulldatewithtime': '2013-01-08T10:25:46',
  'date': '2013-01-08'},
 {'trans_id': 'T01049881',
  'account_id': 'A00003592',
  'type': 'Credit',
  'amount': 600.0,
  'balance': 600.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '13:49:31',
  'fulldatewithtime': '2013-01-08T13:49:31',
  'date': '2013-01-08'},
 {'trans_id': 'T01132662',
  'account_id': 'A00003871',
  'type': 'Credit',
  'amount': 300.0,
  'balance': 300.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '14:07:56',
  'fulldatewithtime': '2013-01-08T14:07:56',
  'date': '2013-01-08'},
 {'trans_id': 'T01021120',
  'account_id': 'A00003487',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 8,
  'fulldate': '2013-01-08',
  'fulltime': '08:08:38',
  'fulldatewithtime': '2013-01-08T08:08:38',
  'date': '2013-01-08'},
 {'trans_id': 'T00439035',
  'account_id': 'A00001493',
  'type': 'Credit',
  'amount': 200.0,
  'balance': 200.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '09:39:13',
  'fulldatewithtime': '2013-01-09T09:39:13',
  'date': '2013-01-09'},
 {'trans_id': 'T00110534',
  'account_id': 'A00000374',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '09:09:09',
  'fulldatewithtime': '2013-01-09T09:09:09',
  'date': '2013-01-09'},
 {'trans_id': 'T00771036',
  'account_id': 'A00002632',
  'type': 'Credit',
  'amount': 14264.0,
  'balance': 15364.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '09:27:45',
  'fulldatewithtime': '2013-01-09T09:27:45',
  'date': '2013-01-09'},
 {'trans_id': 'T00506450',
  'account_id': 'A00001730',
  'type': 'Credit',
  'amount': 900.0,
  'balance': 900.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '11:42:16',
  'fulldatewithtime': '2013-01-09T11:42:16',
  'date': '2013-01-09'},
 {'trans_id': 'T00192097',
  'account_id': 'A00000652',
  'type': 'Credit',
  'amount': 13851.0,
  'balance': 14551.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '16:46:01',
  'fulldatewithtime': '2013-01-09T16:46:01',
  'date': '2013-01-09'},
 {'trans_id': 'T01117248',
  'account_id': 'A00003818',
  'type': 'Credit',
  'amount': 17366.0,
  'balance': 17966.0,
  'year': 2013,
  'month': 1,
  'day': 9,
  'fulldate': '2013-01-09',
  'fulltime': '08:09:03',
  'fulldatewithtime': '2013-01-09T08:09:03',
  'date': '2013-01-09'},
 {'trans_id': 'T00695720',
  'account_id': 'A00002379',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 10,
  'fulldate': '2013-01-10',
  'fulltime': '15:55:39',
  'fulldatewithtime': '2013-01-10T15:55:39',
  'date': '2013-01-10'},
 {'trans_id': 'T00857973',
  'account_id': 'A00002925',
  'type': 'Credit',
  'amount': 1000.0,
  'balance': 1000.0,
  'year': 2013,
  'month': 1,
  'day': 10,
  'fulldate': '2013-01-10',
  'fulltime': '12:19:11',
  'fulldatewithtime': '2013-01-10T12:19:11',
  'date': '2013-01-10'},
 {'trans_id': 'T00477638',
  'account_id': 'A00001628',
  'type': 'Credit',
  'amount': 700.0,
  'balance': 700.0,
  'year': 2013,
  'month': 1,
  'day': 10,
  'fulldate': '2013-01-10',
  'fulltime': '08:10:26',
  'fulldatewithtime': '2013-01-10T08:10:26',
  'date': '2013-01-10'},
 {'trans_id': 'T01049882',
  'account_id': 'A00003592',
  'type': 'Credit',
  'amount': 6007.0,
  'balance': 6607.0,
  'year': 2013,
  'month': 1,
  'day': 10,
  'fulldate': '2013-01-10',
  'fulltime': '09:02:13',
  'fulldatewithtime': '2013-01-10T09:02:13',
  'date': '2013-01-10'},
 {'trans_id': 'T00252644',
  'account_id': 'A00000866',
  'type': 'Credit',
  'amount': 500.0,
  'balance': 500.0,
  'year': 2013,
  'month': 1,
  'day': 10,
  'fulldate': '2013-01-10',
  'fulltime': '10:45:25',
  'fulldatewithtime': '2013-01-10T10:45:25',
  'date': '2013-01-10'},
 {'trans_id': 'T00393505',
  'account_id': 'A00001338',
  'type': 'Credit',
  'amount': 400.0,
  'balance': 400.0,
  'year': 2013,
  'month': 1,
  'day': 11,
  'fulldate': '2013-01-11',
  'fulltime': '08:34:56',
  'fulldatewithtime': '2013-01-11T08:34:56',
  'date': '2013-01-11'},
 {'trans_id': 'T00171813',
  'account_id': 'A00000576',
  'type': 'Credit',
  'amount': 6207.0,
  'balance': 7107.0,
  'year': 2013,
  'month': 1,
  'day': 11,
  'fulldate': '2013-01-11',
  'fulltime': '16:36:38',
  'fulldatewithtime': '2013-01-11T16:36:38',
  'date': '2013-01-11'},
 {'trans_id': 'T00581699',
  'account_id': 'A00001979',
  'type': 'Credit',
  'amount': 900.0,
  'balance': 900.0,
  'year': 2013,
  'month': 1,
  'day': 11,
  'fulldate': '2013-01-11',
  'fulltime': '12:20:47',
  'fulldatewithtime': '2013-01-11T12:20:47',
  'date': '2013-01-11'},
 {'trans_id': 'T00252645',
  'account_id': 'A00000866',
  'type': 'Credit',
  'amount': 12644.0,
  'balance': 13144.0,
  'year': 2013,
  'month': 1,
  'day': 11,
  'fulldate': '2013-01-11',
  'fulltime': '15:04:16',
  'fulldatewithtime': '2013-01-11T15:04:16',
  'date': '2013-01-11'},
 {'trans_id': 'T00101386',
  'account_id': 'A00000346',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 11,
  'fulldate': '2013-01-11',
  'fulltime': '11:25:35',
  'fulldatewithtime': '2013-01-11T11:25:35',
  'date': '2013-01-11'},
 {'trans_id': 'T00689828',
  'account_id': 'A00002357',
  'type': 'Credit',
  'amount': 6434.0,
  'balance': 7234.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '10:30:16',
  'fulldatewithtime': '2013-01-12T10:30:16',
  'date': '2013-01-12'},
 {'trans_id': 'T00725752',
  'account_id': 'A00002484',
  'type': 'Credit',
  'amount': 14779.0,
  'balance': 15879.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '16:47:37',
  'fulldatewithtime': '2013-01-12T16:47:37',
  'date': '2013-01-12'},
 {'trans_id': 'T00565655',
  'account_id': 'A00001926',
  'type': 'Credit',
  'amount': 4507.0,
  'balance': 5207.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '13:52:16',
  'fulldatewithtime': '2013-01-12T13:52:16',
  'date': '2013-01-12'},
 {'trans_id': 'T00857974',
  'account_id': 'A00002925',
  'type': 'Credit',
  'amount': 6446.0,
  'balance': 7446.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '12:34:59',
  'fulldatewithtime': '2013-01-12T12:34:59',
  'date': '2013-01-12'},
 {'trans_id': 'T00560898',
  'account_id': 'A00001909',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '14:13:45',
  'fulldatewithtime': '2013-01-12T14:13:45',
  'date': '2013-01-12'},
 {'trans_id': 'T00207265',
  'account_id': 'A00000704',
  'type': 'Credit',
  'amount': 17477.0,
  'balance': 18477.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '11:04:49',
  'fulldatewithtime': '2013-01-12T11:04:49',
  'date': '2013-01-12'},
 {'trans_id': 'T00477639',
  'account_id': 'A00001628',
  'type': 'Credit',
  'amount': 4276.0,
  'balance': 4976.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '11:14:10',
  'fulldatewithtime': '2013-01-12T11:14:10',
  'date': '2013-01-12'},
 {'trans_id': 'T00615542',
  'account_id': 'A00002099',
  'type': 'Credit',
  'amount': 1100.0,
  'balance': 1100.0,
  'year': 2013,
  'month': 1,
  'day': 12,
  'fulldate': '2013-01-12',
  'fulltime': '13:13:38',
  'fulldatewithtime': '2013-01-12T13:13:38',
  'date': '2013-01-12'},
 {'trans_id': 'T00439036',
  'account_id': 'A00001493',
  'type': 'Credit',
  'amount': 5009.0,
  'balance': 5209.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '14:38:37',
  'fulldatewithtime': '2013-01-13T14:38:37',
  'date': '2013-01-13'},
 {'trans_id': 'T01100759',
  'account_id': 'A00003760',
  'type': 'Credit',
  'amount': 1000.0,
  'balance': 1000.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '15:18:01',
  'fulldatewithtime': '2013-01-13T15:18:01',
  'date': '2013-01-13'},
 {'trans_id': 'T00480215',
  'account_id': 'A00001637',
  'type': 'Credit',
  'amount': 5718.0,
  'balance': 6218.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '14:23:02',
  'fulldatewithtime': '2013-01-13T14:23:02',
  'date': '2013-01-13'},
 {'trans_id': 'T01548749',
  'account_id': 'A00005270',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '13:11:54',
  'fulldatewithtime': '2013-01-13T13:11:54',
  'date': '2013-01-13'},
 {'trans_id': 'T00505241',
  'account_id': 'A00001726',
  'type': 'Credit',
  'amount': 13967.0,
  'balance': 14967.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '12:29:39',
  'fulldatewithtime': '2013-01-13T12:29:39',
  'date': '2013-01-13'},
 {'trans_id': 'T00846007',
  'account_id': 'A00002881',
  'type': 'Credit',
  'amount': 6959.0,
  'balance': 7659.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '14:39:11',
  'fulldatewithtime': '2013-01-13T14:39:11',
  'date': '2013-01-13'},
 {'trans_id': 'T01021121',
  'account_id': 'A00003487',
  'type': 'Credit',
  'amount': 15914.0,
  'balance': 16714.0,
  'year': 2013,
  'month': 1,
  'day': 13,
  'fulldate': '2013-01-13',
  'fulltime': '13:39:09',
  'fulldatewithtime': '2013-01-13T13:39:09',
  'date': '2013-01-13'},
 {'trans_id': 'T02908689',
  'account_id': 'A00009635',
  'type': 'Credit',
  'amount': 4470.0,
  'balance': 4870.0,
  'year': 2013,
  'month': 1,
  'day': 14,
  'fulldate': '2013-01-14',
  'fulltime': '14:50:59',
  'fulldatewithtime': '2013-01-14T14:50:59',
  'date': '2013-01-14'},
 {'trans_id': 'T00858384',
  'account_id': 'A00002926',
  'type': 'Credit',
  'amount': 600.0,
  'balance': 600.0,
  'year': 2013,
  'month': 1,
  'day': 14,
  'fulldate': '2013-01-14',
  'fulltime': '10:12:59',
  'fulldatewithtime': '2013-01-14T10:12:59',
  'date': '2013-01-14'},
 {'trans_id': 'T00498389',
  'account_id': 'A00001699',
  'type': 'Credit',
  'amount': 800.0,
  'balance': 800.0,
  'year': 2013,
  'month': 1,
  'day': 14,
  'fulldate': '2013-01-14',
  'fulltime': '14:55:00',

In [26]:
#creating new database in mongodb
db = client["GDDA707"]

In [27]:
print(db)

Database(MongoClient(host=['ac-btjms2e-shard-00-00.s7xdaor.mongodb.net:27017', 'ac-btjms2e-shard-00-02.s7xdaor.mongodb.net:27017', 'ac-btjms2e-shard-00-01.s7xdaor.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='MongoDBCluster', authsource='admin', replicaset='atlas-sbhm9z-shard-0', tls=True), 'GDDA707')

In [28]:
#insert data into mongodb
db.GDDA707A2.insert_many(data_list)

AutoReconnect: ac-btjms2e-shard-00-02.s7xdaor.mongodb.net:27017: (10054, 'WSAECONNRESET') (configured timeouts: connectTimeoutMS: 20000.0ms)

In [ ]:
#close the mongodb connection
client.close()